version: '3'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=hunt-db
      - MYSQL_USER=biighunter
      - MYSQL_PASSWORD=1122
      - MYSQL_ROOT_PASSWORD=1122
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: